### PR TITLE
Updated the User Interface of Signup and Login Pages.

### LINKED ISSUE #4: Sign up and Login page
Login and Sign-up pages added, UI need to be improved

### PR DESCRIPTION
**Pull request by amitpola**
Screenshot_2020-12-12-14-27-57-94_5222504a9b4de14cd7dea626e3c6cb48
Screenshot_2020-12-12-14-28-01-14_5222504a9b4de14cd7dea626e3c6cb48

### CODE REVIEW

**Comment by utkarsh0702** [comment]
@amitpola I went through the files and saw that you have removed the validations from the login.dart and signup.dart files. Please add them.

**Comment by utkarsh0702** [comment]
@amitpola I would also like you to work on category page along with @jsuryakt for creating separate categories for books like Action and Adventure, Classics, Detective and Mystery,etc 
Issue #11

**Comment by amitpola** [comment]
The email and password validations are there and they are working correctly, i ran the login and signup pages

**Comment by amitpola** [comment]
> @amitpola I would also like you to work on category page along with @jsuryakt for creating separate categories for books like Action and Adventure, Classics, Detective and Mystery,etc
> Issue #11

sure !!

**Comment by utkarsh0702** [comment]
@amitpola ok, then I will also assign you issue #11 
Just comment something on that issue.

**Pull request merged**
